name: plotvote
description: "Write the next part of the story, get votes, survive eliminations. Outplot everyone!"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0  #http client for response handling, timeouts etc.
  pretty_dio_logger: ^1.4.0
  socket_io_client: ^3.0.0  #library for websocket
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^8.0.3 #dependency injection library
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  share_plus: ^10.1.0
  flutter_svg: ^2.0.10+1 
  go_router: ^14.3.0 #used for routing navigation

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/productsans-light.ttf
          weight: 300
        - asset: assets/fonts/productsans-lightitalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/productsans-medium.ttf
          weight: 500
        - asset: assets/fonts/productsans-regular.ttf
          weight: 400
        - asset: assets/fonts/productsans-pixel.ttf
          weight: 400

    - family: Nothing
      fonts:
        - asset: assets/fonts/nothing.ttf

    - family: Monument
      fonts:
        - asset: assets/fonts/monument.ttf

    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Black.ttf
        - asset: assets/fonts/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend-ExtraBold.ttf
        - asset: assets/fonts/Lexend-ExtraLight.ttf
        - asset: assets/fonts/Lexend-Light.ttf
        - asset: assets/fonts/Lexend-Medium.ttf
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-SemiBold.ttf
        - asset: assets/fonts/Lexend-Thin.ttf



    - family: Amberes
      fonts:
        - asset: assets/fonts/amberes.ttf 

    - family: Archivo
      fonts:
        - asset: assets/fonts/archivo.ttf

    - family: Geist
      fonts:  
        - asset: assets/fonts/geist.ttf   #too light

    - family: Merriweather
      fonts:
        - asset: assets/fonts/merriweather.ttf    #take

    - family: Merriweatheritalic
      fonts:
        - asset: assets/fonts/merriweatheritalic.ttf

    - family: Montreal
      fonts:
        - asset: assets/fonts/montreal.ttf

    - family: Parabole  #title
      fonts:
        - asset: assets/fonts/parabole.ttf

    